# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "vmd" "xhci_pci" "ahci" "nvme" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/12fb45d9-a332-4292-98da-bb1086869187";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/4375-0BAD";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/9f26741a-8acd-4014-bb79-a6453ccbdcc5";
      fsType = "ext4";
    };

  fileSystems."/storage/secondary" =
    { device = "/dev/disk/by-uuid/804d006f-2df7-4357-bfc5-bb9bd7e36445";
      fsType = "ext4";
    };

  fileSystems."/storage/small" =
    { device = "/dev/disk/by-uuid/3e2c79f4-d0d7-432a-993c-13582b8c6818";
      fsType = "ext4";
    };

  fileSystems."/storage/large" =
    { device = "/dev/disk/by-uuid/336970ea-12ee-49c0-adca-409296ad819a";
      fsType = "ext4";
    };

  fileSystems."/storage/hdd" =
    { device = "/dev/disk/by-uuid/6D981AA53473A12B";
      fsType = "ntfs";
    };

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.eno1.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp7s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
